<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Vinhomes group</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php echo $this->headLink()->appendStylesheet('/bootstrap-3.3.5-dist/css/bootstrap.min.css') ?>
</head>
<body>
  <div id="header" class="col-md-12">
    <?php echo $this->render('_header.phtml') ?>
  </div>
  <div id="right-navigation" class="col-md-3">
    <?php echo $this->render('_right_navigation.phtml') ?>
  </div>
  <div id="main-content" class="col-md-9">
    <?php echo $this->layout()->content; ?>
  </div>
  <div id="footer" class="col-md-12">
    <?php echo $this->render('_footer.phtml') ?>
  </div>
</body>
</html>
